"""Add created_by for nodes, namespaces, and tags

Revision ID: 363991e344b8
Revises: 58e246fba34b
Create Date: 2023-10-23 20:51:40.076102+00:00

"""
# pylint: disable=no-member, invalid-name, missing-function-docstring, unused-import, no-name-in-module

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = '363991e344b8'
down_revision = '58e246fba34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_node_created_by_users'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('nodenamespace', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_nodenamespace_created_by_users'), 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodenamespace', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_nodenamespace_created_by_users'), type_='foreignkey')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_node_created_by_users'), type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
